import { Link } from 'react-router-dom'
import Reveal from '../components/Reveal'
import CtaBand from '../components/CtaBand'
import { identity, vision, process, serviceAreas, industries } from '../data/site'
import './pages.css'
import './About.css'  // Premium About page styling
export default function About(){
  return(<><section className="page-header"><div className="wrap"><span className="eyebrow">About Syntex</span><h1>{identity.tagline}</h1><p className="page-lead">{identity.legal} is a Namibian ICT systems integrator, incorporated in {identity.incorporated} and operating from {identity.region}. We design, integrate and support the security, enterprise and utility systems that organisations across Southern Africa run on.</p></div></section>
  <section className="wrap about-intro"><Reveal className="about-intro-lead"><h2>An engineering partner, not a reseller.</h2></Reveal><Reveal className="about-intro-body" delay={80}><p>Syntex excels at solving complex business and systems problems using a proven process built on best practices and international standards. We deliver complete, end-to-end engagements — project management, change management, business process re-engineering and knowledge transfer — so a system is adopted, not just installed.</p><p>The company works across {serviceAreas.length} verified service areas spanning security, enterprise systems, utility & billing and consulting.</p></Reveal></section>
  <section className="about-facts"><div className="wrap about-facts-grid"><Reveal className="about-fact"><dt>Incorporated</dt><dd>{identity.incorporated}</dd></Reveal><Reveal className="about-fact"><dt>Head office</dt><dd>{identity.region}, {identity.country}</dd></Reveal><Reveal className="about-fact"><dt>Service areas</dt><dd>{serviceAreas.length}</dd></Reveal><Reveal className="about-fact"><dt>Sectors served</dt><dd>{industries.length}</dd></Reveal></div></section>
  <section className="about-vision"><div className="wrap"><Reveal className="about-vision-head"><span className="eyebrow">Vision</span><p className="about-vision-text">{vision.text}</p></Reveal><div className="about-values">{vision.values.map((v,i)=><Reveal key={v.n} delay={i*70} className="about-value"><span className="about-value-n">{v.n}</span><h3>{v.title}</h3><p>{v.text}</p></Reveal>)}</div></div></section>
  <section className="wrap about-process"><Reveal className="about-process-head"><span className="eyebrow">How we work</span><h2>A proven delivery process.</h2></Reveal><ol className="about-steps">{process.map(st=><Reveal as="li" key={st.n} className="about-step"><span className="about-step-n">{st.n}</span><div><h3>{st.title}</h3><p>{st.text}</p></div></Reveal>)}</ol></section>
  <section className="wrap about-more"><div className="about-more-grid">{[['/about/story','Our Story'],['/about/vision-mission','Vision & Mission'],['/about/values','Core Values'],['/about/leadership','Leadership'],['/about/team','Team'],['/about/careers','Careers']].map(([to,l])=><Link key={to} to={to} className="about-more-link">{l} <span aria-hidden="true">→</span></Link>)}</div></section>
  <CtaBand/></>)
}